# Generated by Django 4.1 on 2023-03-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="title",
            field=models.CharField(max_length=10000),
        ),
    ]
