# Generated by Django 4.1 on 2023-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_pdf_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="pdf_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pdf",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
