# Generated by Django 4.1 on 2023-03-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="doc",
            name="txt_file_docx",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="pdf",
            name="txt_file_pdf",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="doc",
            name="doc_file",
            field=models.FileField(upload_to="../myapp/docs/"),
        ),
        migrations.AlterField(
            model_name="pdf",
            name="pdf_file",
            field=models.FileField(upload_to="../myapp/pdfs/"),
        ),
    ]
