# Generated by Django 4.1 on 2023-03-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_doc_txt_file_docx_pdf_txt_file_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doc",
            name="doc_file",
            field=models.FileField(upload_to="myapp_file/docs/"),
        ),
        migrations.AlterField(
            model_name="pdf",
            name="pdf_file",
            field=models.FileField(upload_to="myapp_file/pdfs/"),
        ),
    ]
