# Generated by Django 4.1 on 2023-03-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_doc_doc_file_alter_pdf_pdf_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="XLSX",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("xlsx_file", models.FileField(upload_to="myapp_file/xlsx/")),
                ("xlsx_text", models.TextField(blank=True, null=True)),
                ("txt_file_xlsx", models.FileField(blank=True, upload_to="")),
            ],
        ),
    ]
