# Generated by Django 4.1 on 2023-03-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_xlsx"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text_edited", models.TextField(blank=True)),
                ("txt_file_edited", models.FileField(blank=True, upload_to="")),
            ],
        ),
    ]
