# Generated by Django 4.1 on 2023-04-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_edittext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdf",
            name="pdf_text",
        ),
        migrations.RemoveField(
            model_name="pdf",
            name="txt_file_pdf",
        ),
        migrations.AddField(
            model_name="pdf",
            name="pdf_text_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pdf",
            name="pdf_text_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pdf",
            name="txt_file_pdf_en",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="pdf",
            name="txt_file_pdf_it",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="doc",
            name="doc_file",
            field=models.FileField(upload_to="myapp/upload_file//myapp_file/docs/"),
        ),
        migrations.AlterField(
            model_name="pdf",
            name="pdf_file",
            field=models.FileField(upload_to="myapp/upload_file//myapp_file/pdfs/"),
        ),
        migrations.AlterField(
            model_name="xlsx",
            name="xlsx_file",
            field=models.FileField(upload_to="myapp/upload_file//myapp_file/xlsx/"),
        ),
    ]
