# Generated by Django 4.1 on 2023-04-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_remove_pdf_pdf_text_remove_pdf_txt_file_pdf_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doc",
            name="doc_text",
        ),
        migrations.RemoveField(
            model_name="doc",
            name="txt_file_docx",
        ),
        migrations.RemoveField(
            model_name="xlsx",
            name="txt_file_xlsx",
        ),
        migrations.RemoveField(
            model_name="xlsx",
            name="xlsx_text",
        ),
        migrations.AddField(
            model_name="doc",
            name="docx_text_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doc",
            name="docx_text_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doc",
            name="txt_file_docx_en",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="doc",
            name="txt_file_docx_it",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="xlsx",
            name="txt_file_xlsx_en",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="xlsx",
            name="txt_file_xlsx_it",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="xlsx",
            name="xlsx_text_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="xlsx",
            name="xlsx_text_it",
            field=models.TextField(blank=True, null=True),
        ),
    ]
