# Generated by Django 4.1 on 2023-04-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_ner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ner",
            name="dict_NER",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="ner",
            name="my_dict",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
