# Generated by Django 4.1 on 2023-04-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_ner_dict_ner_alter_ner_my_dict"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ner",
            old_name="txt_file",
            new_name="raw_file",
        ),
        migrations.RemoveField(
            model_name="ner",
            name="dict_NER",
        ),
        migrations.RemoveField(
            model_name="ner",
            name="my_dict",
        ),
    ]
