# Generated by Django 4.1 on 2023-04-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_rename_txt_file_ner_raw_file_remove_ner_dict_ner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ner",
            name="jsondict_str",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ner",
            name="jsonner_str",
            field=models.TextField(blank=True),
        ),
    ]
