# Generated by Django 4.1 on 2023-04-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_ner_jsondict_str_ner_jsonner_str"),
    ]

    operations = [
        migrations.AddField(
            model_name="ner",
            name="jsonHighlights",
            field=models.TextField(blank=True, null=True),
        ),
    ]
