# Generated by Django 4.1 on 2023-04-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_remove_ner_jsonhighlights"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("json", models.FileField(blank=True, upload_to="")),
                ("json_str", models.TextField(blank=True)),
                ("language", models.CharField(max_length=50)),
            ],
        ),
    ]
