# Generated by Django 4.1 on 2023-04-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="entity_model",
            field=models.TextField(blank=True),
        ),
    ]
