# Generated by Django 4.1 on 2023-04-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_config_entity_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="entity_question",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="config",
            name="entity_model",
            field=models.TextField(blank=True, null=True),
        ),
    ]
