# Generated by Django 4.1 on 2023-04-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_config_entity_question_alter_config_entity_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="ner",
            name="entity_model_current",
            field=models.TextField(blank=True, null=True),
        ),
    ]
